const { SlashCommandBuilder, EmbedBuilder } = require("discord.js");
const fetch = require("node-fetch");
module.exports = {
	data: new SlashCommandBuilder()
		.setName("dog")
		.setDescription("Grabs a random dog off the internet."),
	async execute(interaction) {
		const responce = await fetch("https://dog.ceo/api/breeds/image/random");
		const data = await responce.json();
		if (data) {
			const embed = new EmbedBuilder()
				.setColor("#ff6633")
        .setTitle("Doggy")
        .setDescription("Random Dog.")
        .setImage(data.message)
        .setTimestamp()
				.setFooter({
          text: "Generated By SuperNova",
          iconURL: "https://github.com/Colack/SuperNova-Bot/blob/main/assets/Colack_A_supernova_exploding_with_code_fec0a35f-a74b-4317-b3cb-afcc34593082.png?raw=true",
        });
			try {
				await interaction.reply({ embeds: [embed ]});
			} catch (err) {
				await interaction.reply(`Could not gather details.....`);
			}
		}
	}
}
