const { SlashCommandBuilder, EmbedBuilder } = require("discord.js");
const fetch = require("node-fetch");
module.exports = {
	data: new SlashCommandBuilder()
		.setName("location")
		.setDescription("Find a users location")
		.addStringOption((option) =>
      option
        .setName("user")
        .setDescription("The user to find")
        .setRequired(true)
    ),
	async execute(interaction) {
		const responce = await fetch("https://random-data-api.com/api/v2/users");
		const data = await responce.json();
		if (data) {
			const embed = new EmbedBuilder()
				.setColor("#ff6633")
        .setTitle(`Hacking Results for ` + interaction.options.getString("user"))
        .setDescription(`${data.address.coordinates.lat}, ${data.address.coordinates.lng}`)
        .setTimestamp()
				.setFooter({
          text: "Generated By SuperNova",
          iconURL: "https://github.com/Colack/SuperNova-Bot/blob/main/assets/Colack_A_supernova_exploding_with_code_fec0a35f-a74b-4317-b3cb-afcc34593082.png?raw=true",
        });
			try {
				await interaction.reply({ embeds: [embed ]});
			} catch (err) {
				await interaction.reply(`Could not gather details.....`);
			}
		}
	}
}
